spring:
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;
    username: sa
    password: StrongPassword2023!
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect